// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BodyRole = "request" | "response" | "message";

export type BodyStorageKind = "inline" | "blob" | "file";

export type CookieJar = { id: string, workspaceId: string, name: string, createdAt: string, updatedAt: string, };

export type CookieRecord = { id: string, workspaceId: string, jarId: string, name: string, value: string, domain: string, path: string, expiresAt: string | null, secure: boolean, httpOnly: boolean, sameSite: string | null, createdAt: string, updatedAt: string, };

export type Environment = { id: string, workspaceId: string, name: string, variables: Record<string, any>, createdAt: string, updatedAt: string, };

export type Page = { cursor: bigint | null, limit: number, };

export type Protocol = "http" | "graphql" | "grpc" | "web_socket" | "sse";

export type Request = { id: string, workspaceId: string, protocol: Protocol, name: string, description: string, config: Record<string, any>, createdAt: string, updatedAt: string, };

export type RequestNode = { id: string, workspaceId: string, parentId: string | null, requestId: string | null, kind: RequestNodeKind, name: string, sortKey: string, createdAt: string, updatedAt: string, };

export type RequestNodeKind = "folder" | "request";

export type Run = { id: string, workspaceId: string, requestId: string, protocol: Protocol, state: RunState, startedAt: string, completedAt: string | null, statusCode: number | null, error: string | null, };

export type RunBody = { id: string, runId: string, workspaceId: string, eventId: bigint | null, bodyRole: BodyRole, contentType: string | null, byteLength: bigint, storageKind: BodyStorageKind, storageRef: string, createdAt: string, };

export type RunEvent = { id: bigint, runId: string, workspaceId: string, sequence: bigint, kind: RunEventKind, data: Record<string, any>, createdAt: string, };

export type RunEventKind = "log" | "dns" | "connect" | "tls" | "request_snapshot" | "request_headers" | "request_body" | "response_headers" | "response_body" | "message" | "error" | "complete";

export type RunState = "created" | "running" | "completed" | "failed" | "cancelled";

export type SecretMetadata = { id: string, workspaceId: string, name: string, ciphertext: string, metadata: Record<string, any>, createdAt: string, updatedAt: string, };

export type Setting = { key: string, value: any, updatedAt: string, };

export type Workspace = { id: string, name: string, description: string, createdAt: string, updatedAt: string, };
