import type { InvokeArgs } from "@tauri-apps/api/core";
import { invoke } from "@tauri-apps/api/core";

type TauriCmd =
  | "cmd_call_grpc_request_action"
  | "cmd_call_http_request_action"
  | "cmd_call_websocket_request_action"
  | "cmd_call_workspace_action"
  | "cmd_call_folder_action"
  | "cmd_check_for_updates"
  | "cmd_curl_to_request"
  | "cmd_decrypt_template"
  | "cmd_default_headers"
  | "cmd_delete_all_grpc_connections"
  | "cmd_delete_all_http_responses"
  | "cmd_delete_send_history"
  | "cmd_dismiss_notification"
  | "cmd_directory_is_empty"
  | "cmd_export_data"
  | "cmd_format_html"
  | "cmd_format_graphql"
  | "cmd_format_json"
  | "cmd_format_xml"
  | "cmd_get_http_authentication_config"
  | "cmd_get_http_authentication_summaries"
  | "cmd_get_http_response_events"
  | "cmd_get_sse_events"
  | "cmd_get_themes"
  | "cmd_get_workspace_meta"
  | "cmd_git_add_credential"
  | "cmd_git_clone"
  | "cmd_grpc_go"
  | "cmd_grpc_reflect"
  | "cmd_grpc_request_actions"
  | "cmd_http_request_actions"
  | "cmd_websocket_request_actions"
  | "cmd_workspace_actions"
  | "cmd_folder_actions"
  | "cmd_http_request_body"
  | "cmd_http_response_body_bytes"
  | "cmd_http_response_body"
  | "cmd_import_data"
  | "cmd_metadata"
  | "cmd_restart"
  | "cmd_new_child_window"
  | "cmd_new_main_window"
  | "cmd_render_template"
  | "cmd_save_response"
  | "cmd_secure_template"
  | "cmd_send_ephemeral_request"
  | "cmd_send_http_request"
  | "cmd_v2_environment_create"
  | "cmd_v2_environment_delete"
  | "cmd_v2_environment_update"
  | "cmd_v2_folder_create"
  | "cmd_v2_folder_update"
  | "cmd_v2_gc_bodies"
  | "cmd_v2_request_create"
  | "cmd_v2_request_node_delete"
  | "cmd_v2_request_node_move"
  | "cmd_v2_request_update"
  | "cmd_v2_run_delete"
  | "cmd_v2_run_prune"
  | "cmd_v2_run_retention_clear"
  | "cmd_v2_run_retention_get"
  | "cmd_v2_run_retention_set"
  | "cmd_v2_workspace_create"
  | "cmd_v2_workspace_delete"
  | "cmd_template_function_summaries"
  | "cmd_template_function_config"
  | "cmd_v2_environment_get"
  | "cmd_v2_environment_list"
  | "cmd_v2_request_get"
  | "cmd_v2_request_list"
  | "cmd_v2_request_node_get"
  | "cmd_v2_run_bodies"
  | "cmd_v2_run_body_bytes"
  | "cmd_v2_run_events"
  | "cmd_v2_run_get"
  | "cmd_v2_run_list"
  | "cmd_v2_send_request"
  | "cmd_v2_workspace_get"
  | "cmd_v2_workspace_list"
  | "cmd_template_tokens_to_string";

export async function invokeCmd<T>(cmd: TauriCmd, args?: InvokeArgs): Promise<T> {
  // console.log('RUN COMMAND', cmd, args);
  try {
    return await invoke(cmd, args);
  } catch (err) {
    console.warn("Tauri command error", cmd, err);
    throw err;
  }
}
