// This file was generated by lezer-generator. You probably shouldn't edit it.
export const Timeline = 1,
  OutgoingLine = 2,
  OutgoingText = 3,
  Newline = 4,
  IncomingLine = 5,
  IncomingText = 6,
  InfoLine = 7,
  InfoText = 8,
  PlainLine = 9,
  PlainText = 10;
