// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginVersion } from "./gen_search";

export type PluginNameVersion = { name: string, version: string, };

export type PluginSearchResponse = { plugins: Array<PluginVersion>, };

export type PluginUpdatesResponse = { plugins: Array<PluginNameVersion>, };
