// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitCommit = { author: string, when: string, message: string | null, };

export type GitStatus = "added" | "conflict" | "current" | "modified" | "removed" | "renamed" | "type_change";

export type GitStatusEntry = { relaPath: string, status: GitStatus, staged: boolean, prev: string | null, next: string | null, };
