// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateInfo = { replyEventId: string, version: string, downloaded: boolean, };

export type UpdateResponse = { "type": "ack" } | { "type": "action", action: UpdateResponseAction, };

export type UpdateResponseAction = "install" | "skip";

export type WatchResult = { unlistenEvent: string, };

export type YakumoNotification = { timestamp: string, timeout: number | null, id: string, title: string | null, message: string, color: string | null, action: YakumoNotificationAction | null, };

export type YakumoNotificationAction = { label: string, url: string, };
