// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PluginUpdateInfo = { name: string, currentVersion: string, latestVersion: string, };

export type PluginUpdateNotification = { updateCount: number, plugins: Array<PluginUpdateInfo>, };
