// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Environment, Folder, GrpcRequest, HttpRequest, WebsocketRequest, Workspace } from "./gen_models";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * An action that can be performed on an auth configuration
 */
export type AuthAction = { label: string, icon?: string, };

export type CallHttpAuthenticationRequest = { contextId: string, values: { [key in string]?: JsonPrimitive }, method: string, url: string, headers: Array<HttpHeader>, };

export type Color = "primary" | "secondary" | "info" | "success" | "notice" | "warning" | "danger";

export type FormInput = { inputType: string, label: string, helpUrl: string | null, description?: string, placeholder?: string, required?: boolean, secret?: boolean, multiline?: boolean, };

export type GetThemesResponse = { themes: Array<Theme>, };

/**
 * Configuration for a specific authentication type
 */
export type HttpAuthenticationConfig = { 
/**
 * Arguments/inputs for this auth type
 */
args: Array<FormInput>, 
/**
 * Optional actions that can be performed
 */
actions?: Array<AuthAction>, 
/**
 * Source registry ID for the built-in auth provider.
 */
sourceId?: string, };

/**
 * Summary of an available authentication type
 */
export type HttpAuthenticationSummary = { 
/**
 * Unique identifier for this auth type (e.g., "basic", "bearer")
 */
name: string, 
/**
 * Friendly display name
 */
label: string, 
/**
 * Optional description
 */
description?: string, };

export type HttpHeader = { name: string, value: string, };

export type Icon = "alert_triangle" | "check" | "check_circle" | "chevron_down" | "copy" | "info" | "pin" | "search" | "trash" | "_unknown";

export type ImportResources = { workspaces: Array<Workspace>, environments: Array<Environment>, httpRequests: Array<HttpRequest>, websocketRequests: Array<WebsocketRequest>, grpcRequests: Array<GrpcRequest>, folders: Array<Folder>, };

export type ImportResponse = { resources: ImportResources | null, error: string | null, };

export type JsonPrimitive = { "string": string } | { "number": number } | { "boolean": boolean } | "null";

export type RenderPurpose = "preview" | "send";

export type ShowToastRequest = { message: string, color?: Color, icon?: Icon, timeout?: number, };

export type TemplateFunction = { name: string, label: string, description: string | null, args: Array<TemplateFunctionArg>, previewType: TemplateFunctionPreviewType, aliases?: Array<string>, previewArgs?: Array<TemplateFunctionArg>, };

export type TemplateFunctionArg = { name: string, label: string | null, description: string | null, typeName: string, optional: boolean, defaultValue: JsonValue | null, helpUrl: string | null, };

export type TemplateFunctionPreviewType = "text" | "json" | "live";

export type Theme = { 
/**
 * How the theme is identified. This should never be changed
 */
id: string, 
/**
 * The friendly name of the theme to be displayed to the user
 */
label: string, 
/**
 * Whether the theme will be used for dark or light appearance
 */
dark: boolean, 
/**
 * The default top-level colors for the theme
 */
base: ThemeComponentColors, 
/**
 * Optionally override theme for individual UI components for more control
 */
components?: ThemeComponents, };

export type ThemeComponentColors = { surface?: string, surfaceHighlight?: string, surfaceActive?: string, text?: string, textSubtle?: string, textSubtlest?: string, border?: string, borderSubtle?: string, borderFocus?: string, shadow?: string, backdrop?: string, selection?: string, primary?: string, secondary?: string, info?: string, success?: string, notice?: string, warning?: string, danger?: string, };

export type ThemeComponents = { dialog?: ThemeComponentColors, menu?: ThemeComponentColors, toast?: ThemeComponentColors, sidebar?: ThemeComponentColors, responsePane?: ThemeComponentColors, appHeader?: ThemeComponentColors, button?: ThemeComponentColors, banner?: ThemeComponentColors, templateTag?: ThemeComponentColors, urlBar?: ThemeComponentColors, editor?: ThemeComponentColors, input?: ThemeComponentColors, };
