// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type APIErrorResponsePayload = { error: string, message: string, };

export type ActivateLicenseRequestPayload = { licenseKey: string, appVersion: string, appPlatform: string, };

export type ActivateLicenseResponsePayload = { activationId: string, };

export type DeactivateLicenseRequestPayload = { appVersion: string, appPlatform: string, };

export type LicenseCheckStatus = { "status": "personal_use", "data": { trial_ended: string, } } | { "status": "trialing", "data": { end: string, } } | { "status": "error", "data": { message: string, code: string, } } | { "status": "active", "data": { periodEnd: string, cancelAt: string | null, } } | { "status": "inactive", "data": { status: string, } } | { "status": "expired", "data": { changes: number, changesUrl: string | null, billingUrl: string, periodEnd: string, } } | { "status": "past_due", "data": { billingUrl: string, periodEnd: string, } };
